name: Martyn Jacques
bio: 'Software Engineer, UK'
picture: 'assets/images/profile.jpg'

url: https://martynjacques.github.io
permalink: /:title/

linkedin: martynjacques
github: MartynJacques

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, _site, src]

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com
